project:
  type: website
  preview:
    port: 6066
website:
  title: "Support technique"
  image: assets/img/logo3.png

  navbar:
    logo: assets/img/logo3.png
    logo-alt: "BQ logo"
    title: false
    collapse-below: lg
    tools:
      - icon: github
        href: https://github.com/BiodiversiteQuebec
        text: dev_support GitHub
    left:
      - text: "Accueil"
        file: index.qmd
      - text: "Portails"
        file: docs/portails/portails_intro.qmd
      - text: "Packages"
        file: docs/packages/packages_intro.qmd
      - text: "Catalogues"
        file: docs/catalogues/catalogues_intro.qmd
      - text: "Serveurs"
        file: docs/serveurs/serveurs_intro.qmd
      - text: "Tableaux de bord"
        file: docs/tableaux_bord/tableaux_bord_intro.qmd
      - text: "Analyses"
        file: docs/analyses/analyses_intro.qmd
      - text: "À propos"
        file: about.qmd
  sidebar:
    - title: "Home"
      style: docked #floating
      background: light
      contents:
        - index.qmd

    ### section portails ###
    - title: "Portails"
      contents:
        - docs/portails/portails_intro.qmd
        - section: "Coleo"
          contents:
            - docs/portails/coleo/coleo_intro.qmd
            - docs/portails/coleo/coleo_structure.qmd
            - docs/portails/coleo/coleo_taxonomie.qmd
            - docs/portails/coleo/coleo_API_endpoints.qmd
        - section: "atlas"
          contents:
            - docs/portails/atlas/atlas_description.qmd
            - docs/portails/atlas/atlas_geoparquet.qmd

    ### section packages ###
    - title: "Packages"
      contents:
        - docs/packages/packages_intro.qmd
        - section: "rcoleo"
          contents:
            - docs/packages/rcoleo/rcoleo_intro.qmd
            - docs/packages/rcoleo/rcoleo_injections.qmd
            - docs/packages/rcoleo/rcoleo_telechargement.qmd
        - section: "ratlas"
          contents:
            - docs/packages/ratlas/ratlas_intro.qmd
        - section: "bdqc_taxa"
          contents:
            - docs/packages/bdqctaxa/bdqc_taxa_intro.qmd
        - section: "gbif_insert"
          contents:
            - docs/packages/gbifinsert/gbif_insert_intro.qmd

    ### section catalogues ###
    - title: "Catalogues"
      contents:
        - docs/catalogues/catalogues_intro.qmd
        - section: "Généralités"
          contents:
            - docs/catalogues/catalogues_s5cmd_use.qmd
        - section: "IO"
          contents:
            - docs/catalogues/io/io_intro.qmd
        - section: "Acer"
          contents:
            - docs/catalogues/acer/acer_intro.qmd
        - section: "GEOIO"
          contents:
            - docs/catalogues/geoio/geoio_intro.qmd

    ### section serveurs ###
    - title: "Serveurs"
      contents:
        - docs/serveurs/serveurs_intro.qmd
        - section: "Rweb"
          contents:
            - docs/serveurs/rweb/rweb_intro.qmd
            - docs/serveurs/rweb/rweb_connect.qmd
            - docs/serveurs/rweb/rweb_shinyapp.qmd

    ### section tableaux bord ###
    - title: "Tableaux de bord"
      contents:
        - docs/tableaux_bord/tableaux_bord_intro.qmd

    ### section analyses ###
    - title: "Analyses"
      contents:
        - docs/analyses/analyses_intro.qmd

    - title: "À propos"
      contents:
        - about.qmd
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
