project:
  type: website

website:
  title: "Support technique"
  image: assets/img/logo3.png

  navbar:
    logo: assets/img/logo3.png
    logo-alt: "BQ logo"
    title: false
    collapse-below: lg
    tools:
      - icon: github
        href: https://github.com/ReseauBiodiversiteQuebec
        text: dev_support GitHub
    left:
      - text: "Accueil"
        file: index.qmd
      - text: "Portails"
        file: portails/portails_intro.qmd
      - text: "Packages"
        file: packages/packages_intro.qmd
      - text: "Analyses"
        file: analyses/analyses_intro.qmd
      - text: "Catalogues"
        file: catalogues/catalogues_intro.qmd
      - text: "Serveurs"
        file: serveurs/serveurs_intro.qmd
      - text: "À propos"
        file: about.qmd
  sidebar:
    - title: "Home"
      style: docked #floating
      background: light
      contents:
        - index.qmd

    ### section portails ###
    - title: "Portails"
      contents:
        - portails/portails_intro.qmd
        - section: "Coleo"
          contents:
            - portails/coleo/coleo_intro.qmd
            - portails/coleo/coleo_structure.qmd
            - portails/coleo/coleo_taxonomie.qmd
            - portails/coleo/coleo_API_endpoints.qmd
        - section: "atlas"
          contents:
            - portails/atlas/atlas_intro.qmd
            - portails/atlas/atlas_geoparquet.qmd

    ### section packages ###
    - title: "Packages"
      contents:
        - packages/packages_intro.qmd
        - section: "rcoleo"
          contents:
            - packages/rcoleo/rcoleo_intro.qmd
            - packages/rcoleo/rcoleo_injections.qmd
            - packages/rcoleo/rcoleo_telechargement.qmd
        - section: "ratlas"
          contents:
            - packages/ratlas/ratlas_intro.qmd
        - section: "bdqc_taxa"
          contents:
            - packages/bdqctaxa/bdqc_taxa_intro.qmd
        - section: "gbif_insert"
          contents:
            - packages/gbifinsert/gbif_insert_intro.qmd

    ### section outils ###
    - title: "Analyses"
      contents:
        - analyses/analyses_intro.qmd

    ### section catalogues ###
    - title: "Catalogues"
      contents:
        - catalogues/catalogues_intro.qmd
        - section: "Généralités"
          contents:
            - catalogues/catalogues_s5cmd_use.qmd
        - section: "IO"
          contents:
            - catalogues/io/io_intro.qmd
        - section: "Acer"
          contents:
            - catalogues/acer/acer_intro.qmd

    ### section serveurs ###
    - title: "Serveurs"
      contents:
        - serveurs/serveurs_intro.qmd
        - section: "Rweb"
          contents:
            - serveurs/rweb/rweb_intro.qmd
            - serveurs/rweb/rweb_connect.qmd
            - serveurs/rweb/rweb_shinyapp.qmd

    - title: "À propos"
      contents:
        - about.qmd
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
