project:
  type: website

website:
  title: "Support technique"
  image: assets/img/logo.png

  navbar:
    logo: assets/img/logo.png
    logo-alt: "BdQc logo"
    title: false
    collapse-below: lg
    tools:
      - icon: github
        href: https://github.com/ReseauBiodiversiteQuebec
        text: dev_support GitHub
    left:
      - text: "Home"
        file: index.qmd
      - text: "Bases de données"
        file: Bdd_intro.qmd
      - text: "Packages"
        file: Packages_intro.qmd
      - text: "Outils"
        file: Outils_intro.qmd
      - text: "Les catalogues"
        file: Catalogues_intro.qmd
      - text: "Serveurs"
        file: Serveurs_intro.qmd
      - text: "À propos"
        file: about.qmd
  sidebar:
    - title: "Home"
      style: docked #floating
      background: light
      contents:
        - index.qmd

    ### section BDD ###
    - title: "Bases de données"
      contents:
        - Bdd_intro.qmd
        - section: "Coleo"
          contents:
            - Coleo_intro.qmd
            - Coleo_structure.qmd
            - Coleo_taxonomie.qmd
            - Coleo_API_endpoints.qmd
        - section: "atlas"
          contents:
            - Atlas_intro.qmd

    ### section packages ###
    - title: "Packages"
      contents:
        - Packages_intro.qmd
        - section: "rcoleo"
          contents:
            - Rcoleo_intro.qmd
            - Rcoleo_injections.qmd
            - Rcoleo_telechargement.qmd
        - section: "ratlas"
          contents:
            - Ratlas_intro.qmd

    ### section outils ###
    - title: "Outils"
      contents:
        - Outils_intro.qmd
        - section: "bdqc_taxa"
          contents:
            - Bdqc_taxa_intro.qmd
        - section: "gbif_insert"
          contents:
            - Gbif_insert_intro.qmd

    ### section catalogues ###
    - title: "Catalogues"
      contents:
        - Catalogues_intro.qmd
        - section: "Généralités"
          contents:
            - Catalogues_s5cmd_use.qmd
        - section: "IO"
          contents:
            - Io_intro.qmd
        - section: "Acer"
          contents:
            - Acer_intro.qmd

    ### section serveurs ###
    - title: "Serveurs"
      contents:
        - Serveurs_intro.qmd
        - section: "Rweb"
          contents:
            - Rweb_intro.qmd
            - Rweb_connect.qmd
            - Rweb_shinyapp.qmd

    - title: "À propos"
      contents:
        - about.qmd
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
