project:
  type: website

website:
  title: "Support technique"
  image: assets/img/logo.png

  navbar:
    logo: assets/img/logo.png
    logo-alt: "BdQc logo"
    title: false
    collapse-below: lg
    tools:
      - icon: github
        href: https://github.com/ReseauBiodiversiteQuebec
        text: dev_support GitHub
    left:
      - text: "Home"
        file: index.qmd
      - text: "Coleo"
        file: Coleo_intro.qmd
      - text: "rcoleo"
        file: Rcoleo_intro.qmd
      - text: "Atlas"
        file: Atlas_intro.qmd
      - text: "ratlas"
        file: Ratlas_intro.qmd
      - text: "bdqc_taxa"
        file: Bdqc_taxa_intro.qmd
      - text: "gbif_insert"
        file: Gbif_insert_intro.qmd
      - text: "Les catalogues"
        file: Catalogues_intro.qmd
      - text: "Rweb"
        file: Rweb_intro.qmd
      - text: "À propos"
        file: about.qmd
  sidebar:
    - title: "Home"
      style: docked #floating
      background: light
      contents:
        - index.qmd

    - title: "Coleo"
      contents:
        - Coleo_intro.qmd
        - Coleo_structure.qmd
        - Coleo_taxonomie.qmd
        - Coleo_API_endpoints.qmd

    - title: "rcoleo"
      contents:
        - Rcoleo_intro.qmd
        - Rcoleo_injections.qmd
        - Rcoleo_telechargement.qmd

    - title: "atlas"
      contents:
        - Atlas_intro.qmd

    - title: "ratlas"
      contents:
        - Ratlas_intro.qmd

    - title: "bdqc_taxa"
      contents:
        - Bdqc_taxa_intro.qmd

    - title: "Les catalogues"
      contents:
        - Catalogues_intro.qmd
        - Catalogues_s5cmd_use.qmd

    - title: "Rweb"
      contents:
        - Rweb_intro.qmd
        - Rweb_connect.qmd
        - Rweb_shinyapp.qmd

    - title: "À propos"
      contents:
        - about.qmd
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
